"use client";

import { BarChart3, Box, Eye, Pencil, Plus, Trash2, TriangleAlert, Upload, X, XCircle } from "lucide-react";
import { useState } from "react";

const initialProducts = [
  ["INV-001", "Cohiba Siglo I", "Cohiba", "Premium", "45", "10", "$40.00", "Approved"],
  ["INV-002", "Arturo Fuente Hemingway", "Arturo Fuente", "Mid", "58", "20", "$7.00", "Under Review"],
  ["INV-003", "Padron 1964 Anniversary", "Padron", "Premium", "42", "11", "$45.00", "Approved"],
  ["INV-004", "Montecristo #2", "Rocky Patel", "Premium", "69", "12", "$30.00", "Denied"],
];
type Modal = "add" | "details" | "delete" | null;

export default function InventoryManager() {
  const [modal, setModal] = useState<Modal>(null);
  const [products, setProducts] = useState(initialProducts);
  const [selected, setSelected] = useState(0);
  const open = (type: Modal, index = 0) => { setSelected(index); setModal(type); };
  const close = () => setModal(null);
  const remove = () => { setProducts(items => items.filter((_, index) => index !== selected)); close(); };

  return <div className="min-h-[calc(100vh-72px)] bg-[#3b2918] p-3 sm:p-4">
    <div className="flex justify-end"><button onClick={()=>open("add")} className="flex h-10 min-w-40 items-center justify-center gap-2 rounded-sm bg-[#d3a440] px-4 text-xs text-[#291806] transition hover:-translate-y-0.5 hover:bg-[#e0b653]"><Plus size={16}/> Add Inventory</button></div>
    <section className="mt-[18px] grid grid-cols-2 gap-2.5 xl:grid-cols-4 xl:gap-4">{[["1,284","Total SKUs",Box],["$124,400","Inventory Value",BarChart3],["7 Items","Low Stock",TriangleAlert],["3 Items","Out of Stock",XCircle]].map(([value,label,Icon])=><article className="flex h-24 items-center justify-between rounded-lg border border-[#e4cf98] bg-[#34200e] p-3 sm:h-[132px] sm:p-5" key={label as string}><div className="flex flex-col"><strong className="text-lg sm:text-[25px]">{value as string}</strong><span className="text-[9px] text-[#a48656]">{label as string}</span></div><Icon className="text-[#f1d89a]" size={36} strokeWidth={1.25}/></article>)}</section>

    <div className="mt-[18px] overflow-x-auto rounded-lg border border-[#745326]"><table className="w-full min-w-[950px] border-collapse bg-[#36220f] text-[10px]"><thead className="bg-[#211305]"><tr>{["Image","SKU","Product Name","Brand","Category","Quantity","Threshold","Retail price","Status","Action"].map(x=><th className="h-9 px-3 text-left text-[8px] font-medium" key={x}>{x}</th>)}</tr></thead><tbody>{products.map((p,index)=><tr key={p[0]}>{<><td className="h-[57px] border-t border-[#6a471f] px-3"><span className="grid h-8 w-10 place-items-center rounded border border-[#8c662d] bg-gradient-to-br from-[#805327] to-[#241306] text-[#e1b64f]">▥</span></td>{p.slice(0,7).map((value,i)=><td className="h-[57px] whitespace-nowrap border-t border-[#6a471f] px-3" key={i}>{i===3?<span className="rounded bg-[#65461e] px-1.5 py-1">{value}</span>:value}</td>)}<td className="h-[57px] border-t border-[#6a471f] px-3"><span className={`inline-block min-w-20 rounded px-1.5 py-1 text-center ${p[7]==="Approved"?"bg-[#0d6c19] text-[#34da66]":p[7]==="Denied"?"bg-[#99373c] text-[#ff9ba0]":"bg-[#987500] text-[#f2c719]"}`}>{p[7]}</span></td><td className="h-[57px] border-t border-[#6a471f] px-3"><span className="flex gap-2.5"><ActionButton label="Edit"><Pencil size={15}/></ActionButton><ActionButton label="View" onClick={()=>open("details",index)}><Eye size={15}/></ActionButton><ActionButton label="Delete" onClick={()=>open("delete",index)}><Trash2 size={15}/></ActionButton></span></td></>}</tr>)}</tbody></table></div>
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-[10px]"><span>Showing 1 to {products.length} of 12 results</span><div className="flex gap-1.5">{["‹","1","2","3","…","8","›"].map(x=><button className={`h-8 w-8 rounded-sm border border-[#8d7144] hover:bg-[#d1a13d] hover:text-[#2a1807] ${x==="1"?"bg-[#d1a13d] text-[#2a1807]":""}`} key={x}>{x}</button>)}</div></div>

    {modal&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#150b04b8] p-5 backdrop-blur-md" onMouseDown={close}><div className={`relative max-h-[90vh] w-full overflow-y-auto rounded-lg bg-[#573621] p-[18px] shadow-2xl ${modal==="add"?"max-w-[560px]":"max-w-[380px]"}`} onMouseDown={e=>e.stopPropagation()}><button onClick={close} className="absolute right-0 top-0 grid h-8 w-8 place-items-center rounded-bl-xl rounded-tr-lg bg-[#d2a23f] text-[#35200c]"><X size={18}/></button>{modal==="add"&&<AddForm close={close}/>} {modal==="details"&&<Details product={products[selected]}/>} {modal==="delete"&&<DeleteConfirm close={close} remove={remove}/>}</div></div>}
  </div>;
}

const control = "h-[34px] rounded bg-[#68462f] px-3 text-[#eadcb9] outline-none";
function AddForm({close}:{close:()=>void}) {const fields=[["Cigar Name","Cohiba Siglo I"],["Brand","Cohiba"],["Wrapper","Natural"],["Strength","Medium"],["Humidor","Select Humidor"],["Shelf","Select Humidor First"],["Category / Vitola","Select"],["Country of Origin","Cuba"],["Price ($)","10"],["Quantity","10"],["Ring Gauge","50"],["Initial Stock","48"]];return <><h2 className="mb-4 text-xl font-semibold text-[#d5a744]">Add New Product</h2><form onSubmit={e=>{e.preventDefault();close()}}><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{fields.map(([label,value],i)=><label className={`flex flex-col gap-1.5 text-[9px] ${i>9?"sm:col-span-2":""}`} key={label}><span>{label}</span>{[2,3,4,5,6].includes(i)?<select className={control} defaultValue={value}><option>{value}</option></select>:<input className={control} defaultValue={value}/>}</label>)}</div><label className="mt-3 flex flex-col gap-1.5 text-[9px]"><span>Image</span><span className="flex h-28 flex-col items-center justify-center gap-2 rounded border border-dashed border-[#dac598]"><Upload size={20}/><small>Upload cigar Image (JPG, PNG)</small></span><input className="hidden" type="file" accept="image/png,image/jpeg"/></label><div className="my-3 flex gap-3 text-[9px]">{["Staff Pick","New Arrival","Daily Feature"].map(x=><label className="flex items-center gap-1" key={x}><input className="accent-[#d1a23f]" type="checkbox"/>{x}</label>)}</div><ModalActions close={close} action="Add"/></form></>}
function Details({product}:{product:string[]}) {const details=[["Cigar Name",product[1]],["Brand",product[2]],["Wrapper","Natural"],["Strength","Medium"],["Humidor","Main"],["Shelf","A-1"],["Category / Vitola","Figurado"],["Country of Origin","Cuba"],["Price ($)",product[6].replace("$","")],["Quantity",product[4]],["Ring Gauge","50"],["Initial Stock","48"]];return <><h2 className="mb-4 text-xl font-semibold text-[#d5a744]">Inventory Details</h2><span className="mb-3 grid h-14 w-14 place-items-center border border-[#8c662d] bg-gradient-to-br from-[#805327] to-[#241306] text-[#e1b64f]">▥</span><div className="grid grid-cols-2 gap-x-7 gap-y-3">{details.map(([key,value])=><div className="flex flex-col" key={key}><span className="text-[8px] text-[#ffe6a9]">{key}</span><strong className="text-[8px] font-normal text-[#bea16b]">{value}</strong></div>)}</div></>}
function DeleteConfirm({close,remove}:{close:()=>void;remove:()=>void}) {return <><h2 className="mb-4 text-xl font-semibold text-[#d5a744]">Delete a Inventory</h2><span className="grid h-8 w-8 place-items-center rounded-full bg-[#6c4a24]"><TriangleAlert size={15} className="text-[#e0ae45]"/></span><h3 className="mt-3 text-[10px]">Are You Sure?</h3><p className="mt-1 text-[8px] text-[#c6ad7e]">Are you sure you want to delete this inventory?</p><ModalActions close={close} action="Delete" onAction={remove}/></>}
function ModalActions({close,action,onAction}:{close:()=>void;action:string;onAction?:()=>void}) {return <div className="mt-3 grid grid-cols-2 gap-1.5"><button type="button" onClick={close} className="h-8 rounded-sm border border-[#c8983b] text-[9px]">Cancel</button><button type={onAction?"button":"submit"} onClick={onAction} className="h-8 rounded-sm bg-[#d1a23f] text-[9px] text-[#2e1a09]">{action}</button></div>}
function ActionButton({label,onClick,children}:{label:string;onClick?:()=>void;children:React.ReactNode}) {return <button aria-label={label} onClick={onClick} className="text-[#efd89b] transition hover:scale-110 hover:text-[#d3a440]">{children}</button>}
