"use client";

import { Check, Eye, X } from "lucide-react";
import { useState } from "react";

export default function PasswordForm() {
  const [show,setShow] = useState(false);
  const inputClass="h-11 w-full rounded border border-[#d4c091] bg-transparent px-3 pr-11 text-xs outline-none focus:border-[#d2a13d]";
  return <div className="min-h-[calc(100vh-72px)] bg-[#3b2918] p-3 sm:p-5"><section className="relative overflow-hidden rounded-lg bg-[#261407]"><div className="h-32 bg-[linear-gradient(to_bottom,rgba(0,0,0,.25),rgba(45,26,8,.85)),url('/assets/images/footer_bg.png')] bg-cover bg-center"/><div className="relative -mt-12 flex items-end gap-3 px-4 pb-4"><span className="grid h-16 w-16 place-items-center rounded-lg border border-[#d2a13d] bg-[#573621] font-playfair text-lg">CL</span><div><h2 className="font-playfair text-xl font-semibold">The Cigar Lounge</h2><p className="text-[10px] text-[#b89a67]">Premium Retailer · Humidor411 Partner</p></div></div></section><form onSubmit={event=>event.preventDefault()} className="mt-4 rounded-lg border border-[#d4c091] bg-[#59401f] p-4"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><PasswordField label="Current Password" show={show} toggle={()=>setShow(x=>!x)} className={inputClass}/><PasswordField label="New Password" show={show} toggle={()=>setShow(x=>!x)} className={inputClass}/><PasswordField label="Confirm New Password" show={show} toggle={()=>setShow(x=>!x)} className={`${inputClass} border-red-500 sm:col-span-2`} wide/></div><ul className="mt-4 space-y-2 text-[10px] text-[#bda87c]">{[[true,"Minimum 8–12 characters (recommend 12+ for stronger security)."],[true,"At least one uppercase letter must."],[true,"At least one lowercase letter must."],[true,"At least one number must (0–9)."],[false,"At least special character (! @ # $ % ^ & * etc.)."],[false,"No spaces allowed."]].map(([valid,text])=><li className="flex items-center gap-2" key={text as string}>{valid?<Check size={13} className="text-[#8bb89b]"/>:<X size={13} className="text-[#d2a13d]"/>}{text as string}</li>)}</ul><div className="mt-6 flex justify-end gap-2"><button type="button" className="h-10 min-w-28 rounded border border-[#d2a13d] text-xs">Cancel</button><button className="h-10 min-w-28 rounded bg-[#d2a13d] text-xs text-[#291806]">Save Changes</button></div></form></div>;
}
function PasswordField({label,show,toggle,className,wide}:{label:string;show:boolean;toggle:()=>void;className:string;wide?:boolean}){return <label className={`relative flex flex-col gap-1.5 text-[11px] ${wide?"sm:col-span-2":""}`}><span>{label}</span><input type={show?"text":"password"} defaultValue="password123" className={className}/><button type="button" onClick={toggle} className="absolute bottom-3 right-3"><Eye size={16}/></button></label>}
